buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'forge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:1.2-1.1.1'
    }
}

apply plugin: 'forge'
apply from: 'gradle/scripts/getbuildnumber.gradle'

group = 'zmaster587.advancedRocketry'
archivesBaseName = archivebase
sourceCompatibility = 8
targetCompatibility = 8

minecraft {
    version = '1.7.10-10.13.4.1614-1.7.10'
    runDir = 'eclipse/assets'
    replaceIn 'src/main/java/zmaster587/advancedRocketry/AdvancedRocketry.java'
    replace '@MAJOR@', version_major
    replace '@MINOR@', version_minor
    replace '@REVIS@', version_revis
    replace '@QUALIFIER@', version_qualifier
    replace '@BUILD@', project.getBuildNumber()
    replace '%LIBVULPESVERSION%', project.libVulpesVersion
}

apply from: 'gradle/scripts/version.gradle'

jar {
    manifest {
        attributes 'FMLCorePlugin': 'zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin'
        attributes 'FMLCorePluginContainsFMLMod': 'true'
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
    maven {
        name = 'chickenbones'
        url = 'https://chickenbones.net/maven/'
    }
    maven {
        name = 'gt'
        url = 'https://gregtech.overminddl1.com/'
    }
}

dependencies {
    implementation project(':libVulpes')
    def localMicdoodleCore = fileTree(
            dir: 'libs',
            include: ['MicdoodleCore*.jar'])
    def localGalacticraftCore = fileTree(
            dir: 'libs',
            include: ['GalacticraftCore*.jar'])
    if (localMicdoodleCore.isEmpty() || localGalacticraftCore.isEmpty()) {
        implementation 'micdoodle8.mods:MicdoodleCore:1.7-3.0.12.504:Dev'
        implementation 'micdoodle8.mods:GalacticraftCore:1.7-3.0.12.504:Dev'
    }
    else {
        implementation localMicdoodleCore
        implementation localGalacticraftCore
    }
    implementation 'codechicken:CodeChickenLib:1.7.10-1.1.3.140:dev'
    implementation 'codechicken:CodeChickenCore:1.7.10-1.0.7.47:dev'
    implementation 'codechicken:NotEnoughItems:1.7.10-1.0.5.120:dev'
    implementation group: 'com.gregoriust.gregtech',
            name: 'gregtech_1.7.10',
            version: '6.07.12',
            classifier: 'dev'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    filesMatching('mcmod.info') {
        expand version: project.version, mcversion: project.minecraft.version
    }
}

task deobfJar(type: Jar) {
    from sourceSets.main.output
    archiveClassifier.set('deobf')
    destinationDirectory.set(file('output'))
    manifest {
        attributes 'FMLCorePlugin': 'zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin'
        attributes 'FMLCorePluginContainsFMLMod': 'true'
    }
    mustRunAfter 'jar'
}

tasks.build.dependsOn deobfJar
